import express from "express";
import axios from "axios";
import { v4 as uuidv4 } from "uuid";

const router = express.Router();
const IMAGE_URL = "https://qu.ax/lOcWx.jpg";

/* ------------ أدوات المعرّفات والـ headers ------------ */
function randomHex(length) {
  const chars = "abcdef0123456789";
  return Array.from({ length }, () => chars[Math.floor(Math.random() * chars.length)]).join("");
}
function gieneticTrace() {
  return `${randomHex(32)}-${randomHex(16)}`;
}

/* ------------ تسجيل الدخول ------------ */
async function login(deviceId) {
  const res = await axios.post("https://api.sunora.mavtao.com/api/auth/login", { device_id: deviceId }, {
    headers: {
      "user-agent": "Dart/3.4 (gienetic_build)",
      "version": "2.2.2",
      "accept-encoding": "gzip",
      "content-type": "application/json",
      "buildnumber": "105",
      "platform": "android",
      "sentry-trace": gieneticTrace()
    }
  });
  return res.data?.data?.token || null;
}

/* ------------ التحقق من النتائج ------------ */
async function pollResult(xAuth, maxAttempts = 25, delayMs = 15000) {
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      const res = await axios.get("https://api.sunora.mavtao.com/api/music/music_page?page=1&pagesize=50", {
        headers: {
          "user-agent": "Dart/3.4 (gienetic_build)",
          "version": "2.2.2",
          "accept-encoding": "gzip",
          "x-auth": xAuth,
          "buildnumber": "105",
          "platform": "android",
          "sentry-trace": gieneticTrace()
        }
      });

      const records = res.data?.data?.records || [];
      const done = records.filter(r => r.status === "complete");
      if (done.length) {
        return done.map(r => ({
          title: r.title || "Generated by Sunora",
          tags: r.meta_tags,
          prompt: r.meta_prompt,
          audioUrl: r.audio_url,
          videoUrl: r.video_url,
          imageUrl: r.image_url,
          model: r.model_name
        }));
      }
    } catch (e) {
      console.log("Polling error:", e.message);
    }
    await new Promise(r => setTimeout(r, delayMs));
  }
  return [];
}

/* ------------ عملية التوليد ------------ */
async function generateSong(params) {
  const deviceId = uuidv4();
  const token = await login(deviceId);
  if (!token) throw new Error("فشل تسجيل الدخول إلى Sunora");

  const endpoint = "/api/music/custom_generate";
  const payload = {
    title: params.title || "AI Song",
    tags: `${params.style || params.genre || "unknown"}`,
    prompt: params.lyrics || params.desc || ""
  };

  await axios.post("https://api.sunora.mavtao.com" + endpoint, payload, {
    headers: {
      "user-agent": "Dart/3.4 (gienetic_build)",
      "version": "2.2.2",
      "accept-encoding": "gzip",
      "x-auth": token,
      "content-type": "application/json",
      "buildnumber": "105",
      "platform": "android",
      "sentry-trace": gieneticTrace()
    }
  });

  return await pollResult(token);
}

/* ------------ قائمة الأنماط ------------ */
const musicTypes = [
  "pop","rock","jazz","classical","hiphop","rap","rnb","electronic","house","techno",
  "trance","chill","ambient","folk","country","blues","metal","punk","reggae","latin",
  "salsa","tango","afrobeat","kpop","soundtrack","instrumental","lofi","trap","gospel",
  "opera","world","disco","funk"
];

/* ------------ 📡 POST API ------------ */
router.post("/", async (req, res) => {
  try {
    const { desc, genre, gender } = req.body;

    if (!desc) {
      return res.status(400).json({ status: false, message: "⚠️ الوصف مطلوب (desc)" });
    }

    const selectedGenre = genre || "pop";
    const selectedGender = gender || "female";

    const result = await generateSong({
      title: desc.slice(0, 40),
      style: selectedGenre,
      genre: selectedGenre,
      gender: selectedGender,
      lyrics: desc
    });

    if (!result.length)
      return res.status(500).json({ status: false, message: "❌ فشل توليد الأغنية أو لا توجد نتيجة." });

    const song = result[0];

    res.json({
      status: true,
      message: "✅ تم إنشاء الأغنية بنجاح",
      info: {
        title: song.title,
        genre: selectedGenre,
        voice: selectedGender,
        model: song.model,
        prompt: song.prompt
      },
      audioUrl: song.audioUrl,
      videoUrl: song.videoUrl,
      imageUrl: song.imageUrl || IMAGE_URL
    });
  } catch (err) {
    console.error("Sunora API Error:", err);
    res.status(500).json({
      status: false,
      message: "❌ حدث خطأ أثناء التوليد",
      error: err.message
    });
  }
});

/* ------------ 📡 GET API ------------ */
router.get("/", async (req, res) => {
  try {
    const { desc, genre, gender } = req.query;

    if (!desc) {
      return res.status(400).json({ status: false, message: "⚠️ الوصف مطلوب (desc)" });
    }

    const selectedGenre = genre || "pop";
    const selectedGender = gender || "female";

    const result = await generateSong({
      title: desc.slice(0, 40),
      style: selectedGenre,
      genre: selectedGenre,
      gender: selectedGender,
      lyrics: desc
    });

    if (!result.length)
      return res.status(500).json({ status: false, message: "❌ فشل توليد الأغنية أو لا توجد نتيجة." });

    const song = result[0];

    res.json({
      status: true,
      message: "✅ تم إنشاء الأغنية بنجاح",
      info: {
        title: song.title,
        genre: selectedGenre,
        voice: selectedGender,
        model: song.model,
        prompt: song.prompt
      },
      audioUrl: song.audioUrl,
      videoUrl: song.videoUrl,
      imageUrl: song.imageUrl || IMAGE_URL
    });
  } catch (err) {
    console.error("Sunora API Error:", err);
    res.status(500).json({
      status: false,
      message: "❌ حدث خطأ أثناء التوليد",
      error: err.message
    });
  }
});

/* ------------ قائمة الأنواع (اختيار فقط) ------------ */
router.get("/types", (req, res) => {
  res.json({ status: true, types: musicTypes });
});

export default router;